# Generated by Django 4.0.4 on 2022-04-30 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointInPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='описание')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='path',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='path',
            name='points',
            field=models.ManyToManyField(related_name='paths', through='points.PointInPath', to='points.point'),
        ),
        migrations.DeleteModel(
            name='PointPath',
        ),
        migrations.AddField(
            model_name='pointinpath',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.path'),
        ),
        migrations.AddField(
            model_name='pointinpath',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.point'),
        ),
    ]
