# Generated by Django 4.0.5 on 2022-06-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_point_description_report_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
