# Generated by Django 4.0.5 on 2022-06-19 19:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0007_alter_profile_user_alter_report_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Приложение для экскурсоводов', max_length=100)),
                ('background_pattern', models.ImageField(blank=True, null=True, upload_to='images/settings/', verbose_name='паттерн на заднем фоне')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='setting_images/', verbose_name='паттерн на заднем фоне')),
                ('reservation_comment', models.TextField(blank=True, default='', max_length=2000, verbose_name='Комментарий перед формой заказа экскурсии')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=8096, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='pointinpath',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_to_point', to='points.path'),
        ),
        migrations.AlterField(
            model_name='pointinpath',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_to_path', to='points.point'),
        ),
        migrations.CreateModel(
            name='VisitedPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первого посещения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего посещения')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_points', to='points.point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Посещённое место',
                'verbose_name_plural': 'Посещённые места',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveIntegerField(blank=True, default=1, verbose_name='число людей')),
                ('comment', models.TextField(blank=True, default='', max_length=500, verbose_name='дополнительные пожелания')),
                ('contacts', models.TextField(blank=True, default='', max_length=500, verbose_name='Как можно связаться')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Примерная дата для проведения экскурсии')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='points.path', verbose_name='маршрут')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
