# Generated by Django 4.0.5 on 2022-06-20 04:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_setting_point_address_alter_point_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ на экскурсию', 'verbose_name_plural': 'Заказы экскурсий'},
        ),
        migrations.AlterModelOptions(
            name='pointinpath',
            options={'verbose_name': 'Точка на карте', 'verbose_name_plural': 'Точки на карте'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': '      Настройки'},
        ),
        migrations.AddField(
            model_name='profile',
            name='image_md',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/avatars/md/', verbose_name='avatar(md)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_sm',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/avatars/sm/', verbose_name='avatar(sm)'),
        ),
    ]
