# Generated by Django 4.0.5 on 2022-06-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_alter_order_options_alter_pointinpath_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='points',
        ),
        migrations.AddField(
            model_name='pointinpath',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='очередь'),
        ),
    ]
